### ISSUE TITLE
"Lode Runner 3D" incompatible with "Clean HDMI" feature  

### ISSUE THREAD

**Issue by theflynn49** [RobertPeip/Mister64#15]
"Lode Runner 3D" incompatible with "Clean HDMI" feature  
at least on my monitor :) It gives me some kind of blurry screen.

Just to let you know. Rgds.

**Comment by RobertPeip** [comment]
Thanks for the report!

Unfortunatly, not all games will work in that mode. Lode Runner is using a single framebuffer for 480i, so it is not supported for the new output mode. The fallback doesn't work well, but even if it worked, the wouldn't profit at all as it would still be 480i.

**Comment by theflynn49** [comment]
Thank you for the detailed (and fast) explanation !  And also for this impressive core !
Rgds
jF
