### ISSUE TITLE
Error Code on Rom Boot

### ISSUE THREAD

**Issue by ARThornton** [RobertPeip/Mister64#16]
Hello,

First I would like to preface by saying thank you for your work on the N64 core, I truly appreciate it. Secondly I came across an error message when trying to boot an ntsc rom of Duck Dodgers. I know the repository page makes mention that the errors will be displayed in hex with each bit representing something but, im not sure which bits represent what based off the examples. I figure atleast sharing it could help. Please see the below error code. 

65707(2orZ)6d      000001F8
                                 0000040C
                                 0000000C
                                 0000A584
                                 0000d434

Respectfully

![17106460293438196579555003885144](https://github.com/RobertPeip/Mister64/assets/71129695/843d12ed-79d6-4a1b-aef6-994e058c0781)

**Comment by RobertPeip** [comment]
This is an error that is unrelated to the core internal error codes, but instead an error of the game itself
No idea why it occurs for you. Current core build works fine with it.

**Comment by ARThornton** [comment]
I see, thank you for the insight. Maybe I made a bad dump of my rom (though it loads fine and plays through on emulators on my pc). I'll have to dump it again at some point to see. Thank you again.
